# pytorch_lightning==2.0.1
# Deep hybrid GNN-CNN model configuration
# This model combines CNN encoder-decoder architecture with GNN message passing
# at multiple scales, using attention gates for skip connections

seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0005
    weight_decay: 0.0001

model:
  class_path: models.HybridGNNCNNModel
  init_args:
    n_channels: 40
    flatten_temporal_dimension: true
    pos_class_weight: 236  # (relative frequency in augmented 2018 and 2020 fires)^-1
    loss_function: Dice
    base_channels: 64
    num_encoder_blocks: 4
    num_gnn_layers_per_scale: 2
    dropout: 0.15
    use_attention: true

do_train: true
do_test: true
do_predict: false
