# pytorch_lightning==2.0.1
# Small, lightweight GNN model configuration with attention mechanisms
# Optimized for fast training and inference with minimal parameters
# Includes channel and spatial attention for improved feature learning

seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.002  # Slightly higher LR for faster convergence with smaller model

model:
  class_path: models.SmallGNNModel
  init_args:
    n_channels: 40
    flatten_temporal_dimension: true
    pos_class_weight: 236  # (relative frequency in augmented 2018 and 2020 fires)^-1
    loss_function: Dice
    hidden_dim: 32  # Smaller than standard GNN (64)
    num_layers: 2  # Fewer layers than standard GNN (4)
    dropout: 0.05  # Lower dropout for smaller model
    use_attention: true  # Enable channel and spatial attention mechanisms

do_train: true
do_test: true
do_predict: false
